"""Update translation_status_enum

Revision ID: 60b5d4403051
Revises: 9e64114be555
Create Date: 2025-07-05 18:17:04.053212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60b5d4403051'
down_revision = '9e64114be555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_pairs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('pending', 'rejected', 'approved', name='translation_status'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_pairs', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
