"""add augmentation_runs

Revision ID: 713d29c7b4d6
Revises: ad7c20264541
Create Date: 2025-08-15 16:53:43.597387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '713d29c7b4d6'
down_revision = 'ad7c20264541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('augmentation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('queued', 'running', 'succeeded', 'failed', name='augmentation_status'), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runtime_seconds', sa.Numeric(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('augmentation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_augmentation_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_augmentation_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_augmentation_runs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_augmentation_runs_triggered_by'), ['triggered_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('augmentation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_augmentation_runs_triggered_by'))
        batch_op.drop_index('ix_augmentation_runs_status_created')
        batch_op.drop_index(batch_op.f('ix_augmentation_runs_status'))
        batch_op.drop_index(batch_op.f('ix_augmentation_runs_created_at'))

    op.drop_table('augmentation_runs')
    # ### end Alembic commands ###
