"""Add reviewer_id to translation_pairs

Revision ID: c5235cf25249
Revises: 5f7d92d05e7d
Create Date: 2025-07-05 17:50:51.174702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5235cf25249'
down_revision = '5f7d92d05e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_pairs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reviewer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_pairs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reviewer_id')

    # ### end Alembic commands ###
