"""Add indexes for better performance on large datasets

Revision ID: e979871205f9
Revises: 60b5d4403051
Create Date: 2025-07-07 00:58:27.500917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e979871205f9'
down_revision = '60b5d4403051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_recordings_language_id'), ['language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_recordings_translation_id'), ['translation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_recordings_uploaded_at'), ['uploaded_at'], unique=False)

    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_iso_code'), ['iso_code'], unique=False)

    with op.batch_alter_table('translation_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_pairs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_pairs_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_pairs_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_pairs_source_lang_id'), ['source_lang_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_pairs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_pairs_target_lang_id'), ['target_lang_id'], unique=False)
        batch_op.create_index('ix_translationpair_created_status', ['created_at', 'status'], unique=False)
        batch_op.create_index('ix_translationpair_domain_status', ['domain', 'status'], unique=False)
        batch_op.create_index('ix_translationpair_lang_status', ['source_lang_id', 'status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    with op.batch_alter_table('translation_pairs', schema=None) as batch_op:
        batch_op.drop_index('ix_translationpair_lang_status')
        batch_op.drop_index('ix_translationpair_domain_status')
        batch_op.drop_index('ix_translationpair_created_status')
        batch_op.drop_index(batch_op.f('ix_translation_pairs_target_lang_id'))
        batch_op.drop_index(batch_op.f('ix_translation_pairs_status'))
        batch_op.drop_index(batch_op.f('ix_translation_pairs_source_lang_id'))
        batch_op.drop_index(batch_op.f('ix_translation_pairs_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_translation_pairs_domain'))
        batch_op.drop_index(batch_op.f('ix_translation_pairs_created_at'))

    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_iso_code'))

    with op.batch_alter_table('audio_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_recordings_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_audio_recordings_translation_id'))
        batch_op.drop_index(batch_op.f('ix_audio_recordings_language_id'))

    # ### end Alembic commands ###
